name: Auto Codex Review

# 手動実行のみ。明示的な確認とラベルがない限り投稿しない。
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'レビューを依頼する PR 番号'
        required: true
        type: number
      confirm:
        description: '本当に @codex review を投稿する'
        required: true
        default: false
        type: boolean

jobs:
  request:
    # 明示的な confirm が true のときのみ実行
    if: ${{ inputs.confirm == true }}
    runs-on: ubuntu-latest
    permissions:
      issues: write # コメント投稿に必要。ほかは最小権限。
      pull-requests: read
      contents: read
    steps:
      - name: Post @codex review only when labeled
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = Number(core.getInput('pr_number'))
            // PR が存在するか確認
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            })

            // ラベル確認（codex:review が必須）
            const labels = pr.data.labels.map(l => l.name)
            const REQUIRED_LABEL = 'codex:review'
            const hasLabel = labels.includes(REQUIRED_LABEL)
            core.info(`labels: ${labels.join(', ')}`)
            if (!hasLabel) {
              core.notice(`ラベル '${REQUIRED_LABEL}' が無いため投稿をスキップします。`)
              return
            }

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `@codex review\n\n日本語でレビューしてください。Please respond in Japanese.`
            })
