name: CI (push)

on:
  push:
    branches: [main, 'feat/**', 'fix/**', 'chore/**', 'ci/**']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --no-audit --no-fund

      - name: Lint
        run: npx --yes eslint -c eslint.config.mjs . --ext js

      - name: Format (check only)
        run: npm run format:check

      - name: Test
        run: npm test -- --run
