name: Deploy (production)

on:
  push:
    branches: [main]
  workflow_dispatch: {}

concurrency:
  group: deploy-prod
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: [self-hosted, dailylog-prod]
    timeout-minutes: 15
    environment: production
    steps:
      - name: Show host info
        run: |
          echo "runner:" $(uname -a)
          node -v || true
          npm -v || true
      - name: Pull latest and install prod deps
        working-directory: /srv/dailylog
        run: |
          set -euxo pipefail
          git fetch --prune --quiet origin
          git reset --hard origin/main
          npm ci --omit=dev || npm ci --only=production
      - name: Restart service
        run: |
          sudo systemctl restart dailylog
          sleep 2
          systemctl is-active --quiet dailylog
      - name: Health check (200 or 401 is OK)
        env:
          PORT: 3002
        run: |
          set -euxo pipefail
          CODE=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:${PORT}/api/health || true)
          if [ "$CODE" = "200" ] || [ "$CODE" = "401" ]; then
            echo "Service reachable with HTTP $CODE"
          else
            echo "Unexpected health status: $CODE" >&2
            exit 1
          fi
